services:

  ros:
    build:
      context: .
      dockerfile: ros_ws/Dockerfile
    container_name: shopassist_ros
    network_mode: host
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - MONGO_URI=mongodb://localhost:27017
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/mudit/major-project/map:/home/mudit/major-project/map
      - /home/mudit/major-project/map:/root/major-project/map
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: shopassist_frontend
    ports:
      - "5173:5173"
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: shopassist_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-seed:/mongo-seed
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
